apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal-deployment
  labels:
    app: cal-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cal-deployment
  template:
    metadata:
      labels:
        app: cal-deployment
    spec:
      containers:
      - name: cal-deployment
        image: rajeevmagar/calculator:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cal-service
spec:
  selector:
    app.kubernetes.io/name: cal-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
type: LoadBalancer
